class riscv_environment;

    riscv_driver     drv;
    riscv_monitor    mon;
    riscv_scoreboard scb;

    mailbox mon2scb;

    virtual riscv_if vif;

    // Event generated by monitor when program finishes
    event test_done;


    function new(virtual riscv_if vif);

        this.vif = vif;

        // Create mailbox
        mon2scb = new();

        // Create verification components
        drv = new(vif);

        // Pass event to monitor
        mon = new(vif, mon2scb, test_done);

        scb = new(mon2scb);

    endfunction


    task run();

        $display("\n==============================================");
        $display("          STARTING VERIFICATION");
        $display("==============================================\n");


        // Start driver, monitor and scoreboard
        fork

            drv.run();

            mon.run();

            scb.run();

        join_none


        // ------------------------------------------------
        // Wait until monitor detects JAL x0,0
        // ------------------------------------------------
        @test_done;


        // Give scoreboard a small amount of time to
        // consume the final transaction from mailbox.
        #1;


        // ------------------------------------------------
        // Final verification report
        // ------------------------------------------------
        $display("\n==============================================");
        $display("          VERIFICATION COMPLETE");
        $display("==============================================");

        $display("Instructions Checked: %0d", scb.checked_count);
        $display("Errors Detected:      %0d", scb.error_count);

        $display("==============================================\n");

    endtask

endclass
